#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_systemd_socket

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

if ynh_hide_warnings yunohost service status "$app-celery" >/dev/null; then
	yunohost service remove "$app-celery"
fi

ynh_config_remove_systemd
ynh_config_remove_systemd "$app-celery"

ynh_config_remove_logrotate

ynh_config_remove_nginx

#=================================================
# REMOVE XXHASH
#=================================================
ynh_script_progression "Removing xxHash..."

tempdir="$(mktemp -d)"
ynh_setup_source --dest_dir=$tempdir --source_id="libxxhash"
pushd $tempdir
	make
	make uninstall
popd
ynh_safe_rm "$tempdir"

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

ynh_safe_rm "/var/run/$app-celery"

ynh_redis_remove_db

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
